title: ComputerCrashers
description: "Class of 2026"
owner_name: Open Coding Society
github_username: open-coding-society
github_repo: "pages"
baseurl: "/ComputerCrashers_Lessons"
url: "https://spacegirl13.github.io"
future: true

# Remote theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Header pages
header_pages:
  - navigation/section/csse.md
  - navigation/section/csp.md
  - navigation/section/csa.md
  - navigation/blog.md
  - navigation/search.md
  - navigation/logintoolkit.md